# 2023-12-25 17:09 test2
robot_cfg:
  kinematics:
    # use_usd_kinematics: False
    usd_path: "robot/galbot_zero_with_galbot_one_arm/galbot_zero_with_galbot_one_arm.usd"
    usd_robot_root: "/galbot_zero_with_galbot_one_arm"
    # usd_flip_joints: {"joint1": "Z", "joint2": "Z", "joint3": "Z", "joint4": "Z", "joint5": "Z", "joint6": "Z", "joint7": "Z"}
    isaac_usd_path: ""
    usd_flip_joint_limits: []

    urdf_path: "robot/galbot_zero_with_galbot_one_arm/galbot_zero_with_galbot_one_arm.urdf"
    asset_root_path: "robot/galbot_zero_with_galbot_one_arm"

    base_link: "base_link"
    ee_link: "suction_cup_tcp_link"

    link_names: null
    lock_joints:
      { "lift_joint": 0.5078 }

    extra_links:
      {
        "attached_object":
          {
            "parent_link_name": "suction_cup_tcp_link",
            "link_name": "attached_object",
            "fixed_transform":
              [0, 0, 0, 1, 0, 0, 0],
            "joint_type": "FIXED",
            "joint_name": "attach_joint",
          },
      }

    collision_link_names:
      [
        "hexman_chassis_base_link",
        "lift_base_link",
        "body_lift_link",
        "head_pitch_link",
        "left_arm_base_link",
        "right_arm_base_link",
        "right_arm_link1",
        "right_arm_link2",
        "right_arm_link3",
        "right_arm_link4",
        "right_arm_link5",
        "right_arm_link6",
        "right_arm_link7",
        "right_arm_camera_link",
        "suction_cup_tcp_link",
        "attached_object",
      ]
    collision_spheres:
      hexman_chassis_base_link:
        - "center": [0.0, 0.0, 0.047]
          "radius": 0.3
      lift_base_link:
        - "center": [-0.035, 0.0, 0.228]
          "radius": 0.08
        - "center": [-0.035, 0.0, 0.913]
          "radius": 0.08
        - "center": [-0.035, 0.0, 0.365]
          "radius": 0.08
        - "center": [-0.035, 0.0, 0.502]
          "radius": 0.08
        - "center": [-0.035, 0.0, 0.639]
          "radius": 0.08
        - "center": [-0.035, 0.0, 0.776]
          "radius": 0.08
      body_lift_link:
        - "center": [-0.039, 0.0, 0.331]
          "radius": 0.08
        - "center": [-0.039, 0.0, 0.187]
          "radius": 0.08
      head_pitch_link:
        - "center":
            [0.031, 0.019, -0.039]
          "radius": 0.1
      left_arm_base_link:
        - "center": [0.0, 0.0, 0.592]
          "radius": 0.6
      right_arm_base_link:
        - "center": [0.0, 0.0, 0.047]
          "radius": 0.05
      right_arm_link1:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.05
      right_arm_link2:
        - "center": [0.0, 0.166, 0.0]
          "radius": 0.04
        - "center": [0.0, 0.096, 0.0]
          "radius": 0.04
      right_arm_link3:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.04
        - "center": [0.0, 0.0, -0.055]
          "radius": 0.02
        - "center": [0.0, 0.0, -0.089]
          "radius": 0.02
      right_arm_link4:
        - "center": [0.0, 0.087, 0.0]
          "radius": 0.04
      right_arm_link5:
        - "center": [-0.0, 0.0, -0.147]
          "radius": 0.04
        - "center": [-0.0, -0.044, -0.0]
          "radius": 0.03
        - "center":
            [-0.0, -0.044, -0.083]
          "radius": 0.03
      right_arm_link6:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.04
      right_arm_link7:
        - "center": [0.047, 0.0, 0.015]
          "radius": 0.03
      right_arm_camera_link:
        - "center": [-0.0, 0.01, 0.0]
          "radius": 0.02
        - "center": [-0.0, -0.051, 0.0]
          "radius": 0.02
        - "center": [-0.0, -0.019, -0.0]
          "radius": 0.02
      suction_cup_tcp_link:
        - "center": [0.013, -0.0, -0.0]
          "radius": 0.02
        - "center": [0.207, 0.0, -0.0]
          "radius": 0.02
        - "center": [0.052, -0.0, -0.0]
          "radius": 0.02
        - "center": [0.091, -0.0, -0.0]
          "radius": 0.02
        - "center": [0.129, 0.0, -0.0]
          "radius": 0.02
        - "center": [0.168, 0.0, -0.0]
          "radius": 0.02

    collision_sphere_buffer: 0
    extra_collision_spheres:
      { "attached_object": 3 }

    self_collision_ignore:
      {
        "hexman_chassis_base_link":
          [
            "lift_base_link",
            "body_lift_link",
            "head_pitch_link",
            "left_arm_base_link",
            "right_arm_base_link",
          ],
        "lift_base_link":
          [
            "hexman_chassis_base_link",
            "body_lift_link",
            "head_pitch_link",
            "left_arm_base_link",
            "right_arm_base_link",
          ],

        "body_lift_link":
          [
            "hexman_chassis_base_link",
            "lift_base_link",
            "head_pitch_link",
            "left_arm_base_link",
            "right_arm_base_link",
          ],
        "left_arm_base_link":
          [
            "hexman_chassis_base_link",
            "lift_base_link",
            "body_lift_link",
            "head_pitch_link",
            "right_arm_base_link",
          ],

        "right_arm_base_link":
          [
            "right_arm_link1",
            "lift_base_link",
            "body_lift_link",
          ],
        "right_arm_link1":
          [
            "right_arm_base_link",
            "right_arm_link2",
            "right_arm_link3",
          ],
        "right_arm_link2":
          [
            "right_arm_link1",
            "right_arm_link3",
            "right_arm_link4",
          ],
        "right_arm_link3":
          [
            "right_arm_link2",
            "right_arm_link4",
            "right_arm_link5",
          ],
        "right_arm_link4":
          [
            "right_arm_link3",
            "right_arm_link5",
            "right_arm_link6",
          ],
        "right_arm_link5":
          [
            "right_arm_link4",
            "right_arm_link6",
            "right_arm_link7",
          ],
        "right_arm_link6":
          [
            "right_arm_link5",
            "right_arm_link7",
            "suction_cup_tcp_link",
          ],
        "right_arm_link7":
          [
            "right_arm_link6",
            "right_arm_camera_link",
          ],
        "right_arm_camera_link":
          ["right_arm_link7"],
        "suction_cup_tcp_link":
          [
            "right_arm_link6",
            "right_arm_link7",
            "attached_object",
          ],
        "attached_object":
          ["suction_cup_tcp_link"],
      }

    self_collision_buffer:
      {
        "hexman_chassis_base_link": 0.0,
        "lift_base_link": 0.0,
        "body_lift_link": 0.0,
        "head_pitch_link": 0.0,
        "left_arm_base_link": 0.0,
        "right_arm_base_link": 0.0,
        "right_arm_link1": 0.0,
        "right_arm_link2": 0.0,
        "right_arm_link3": 0.0,
        "right_arm_link4": 0.0,
        "right_arm_link5": 0.0,
        "right_arm_link6": 0.0,
        "right_arm_link7": 0.0,
        "right_arm_camera_link": 0.0,
        "suction_cup_tcp_link": 0.0,
        "attached_object": 0.0,
      }

    use_global_cumul: True

    mesh_link_names:
      [
        "hexman_chassis_base_link",
        "lift_base_link",
        "body_lift_link",
        "head_pitch_link",
        "left_arm_base_link",
        "right_arm_base_link",
        "right_arm_link1",
        "right_arm_link2",
        "right_arm_link3",
        "right_arm_link4",
        "right_arm_link5",
        "right_arm_link6",
        "right_arm_link7",
        "right_arm_camera_link",
        "suction_cup_tcp_link",
        "attached_object",
      ]

    cspace:
      joint_names:
        [
          "right_arm_joint1",
          "right_arm_joint2",
          "right_arm_joint3",
          "right_arm_joint4",
          "right_arm_joint5",
          "right_arm_joint6",
          "right_arm_joint7",
          "lift_joint",
        ]
      retract_config:
        [
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.5078,
        ]
      null_space_weight:
        [1, 1, 1, 1, 1, 1, 1, 1]
      cspace_distance_weight:
        [1, 1, 1, 1, 1, 1, 1, 1]
      max_jerk: 500.0
      max_acceleration: 15.0
