robot_cfg:
  kinematics:
    use_usd_kinematics: False
    # use_usd_kinematics: False
    usd_path: "robot/galbot_one_arm/galbot_one_arm.usd"
    usd_robot_root: "/galbot_one_arm"
    # usd_flip_joints: {"joint1": "Z", "joint2": "Z", "joint3": "Z", "joint4": "Z", "joint5": "Z", "joint6": "Z", "joint7": "Z"}
    isaac_usd_path: ""
    usd_flip_joint_limits: []

    urdf_path: "robot/galbot_one_arm/galbot_one_arm.urdf"
    asset_root_path: "robot/galbot_one_arm"

    base_link: "base_link"
    ee_link: "end_effector_link"
    link_names: null
    lock_joints: null
    extra_links: null

    collision_link_names:
      [
        "base_link",
        "link1",
        "link2",
        "link3",
        "link4",
        "link5",
        "link6",
        "link7",
      ]
    collision_spheres:
      base_link:
        - "center": [0.0, 0.0, 0.036]
          "radius": 0.06
      link1:
        - "center": [0.0, 0.0, -0.019]
          "radius": 0.06
      link2:
        - "center": [0.0, 0.119, 0.0]
          "radius": 0.04
        - "center": [0.0, 0.167, 0.0]
          "radius": 0.04
      link3:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.05
        - "center": [0.0, 0.0, -0.073]
          "radius": 0.03
        - "center": [0.0, 0.0, -0.108]
          "radius": 0.03
      link4:
        - "center": [0.0, 0.107, 0.0]
          "radius": 0.03
        - "center": [0.0, 0.07, 0.0]
          "radius": 0.03
      link5:
        - "center": [0.0, 0.0, -0.145]
          "radius": 0.04
        - "center": [0.0, -0.039, 0.0]
          "radius": 0.03
        - "center":
            [0.0, -0.035, -0.133]
          "radius": 0.03
        - "center":
            [0.0, -0.036, -0.089]
          "radius": 0.03
        - "center":
            [0.0, -0.038, -0.044]
          "radius": 0.03
      link6:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.03
      link7:
        - "center": [0.048, 0.0, 0.008]
          "radius": 0.03
    collision_sphere_buffer: 0
    extra_collision_spheres: {}
    self_collision_ignore:
      {
        "base_link": ["link1", "link2"],
        "link1":
          [
            "base_link",
            "link2",
            "link3",
          ],
        "link2":
          ["link1", "link3", "link4"],
        "link3":
          ["link2", "link4", "link5"],
        "link4":
          ["link3", "link5", "link6"],
        "link5":
          ["link4", "link6", "link7"],
        "link6": ["link5", "link7"],
        "link7": ["link5", "link6"],
      }
    self_collision_buffer:
      {
        "base_link": 0,
        "link1": 0,
        "link2": 0,
        "link3": 0,
        "link4": 0,
        "link5": 0,
        "link6": 0,
        "link7": 0,
      }

    use_global_cumul: True
    mesh_link_names:
      [
        "base_link",
        "link1",
        "link2",
        "link3",
        "link4",
        "link5",
        "link6",
        "link7",
      ]

    cspace:
      joint_names:
        [
          "joint1",
          "joint2",
          "joint3",
          "joint4",
          "joint5",
          "joint6",
          "joint7",
        ]
      retract_config:
        [
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
        ]
      null_space_weight:
        [1, 1, 1, 1, 1, 1, 1]
      cspace_distance_weight:
        [1, 1, 1, 1, 1, 1, 1]
      max_jerk: 10.0
      max_acceleration: 1.0
